#POST http://localhost:3000/users/register
#Content-Type: application/json
#
#{
#"full_name" : "Bill Clinton",
#"email" : "bill@clinton.com",
#"password" : "123456"
#}

##
POST http://localhost:3000/accounts/new
Content-Type: application/json

{
  "group_id": 3,
  "user_id": 5

}

