#POST http://localhost:3000/users/register
#Content-Type: application/json
#
#{
#"full_name" : "Jonathan Piterson",
#"email" : "jonathan@p.com",
#"password" : "123456"
#}

###
POST http://localhost:3000/accounts/new
Content-Type: application/json

{
  "group_id": 1,
  "user_id": 1

}

